#!/usr/bin/env bash
#
# Start the docker container shit

set -e -x 

UID="$(id -u)"
xhost "si:localhost:${USER}"

docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
 -v "/run/user/$UID/pulse:/run/user/$UID/pulse:ro" --device=/dev/dri:/dev/dri \
 jaredallard/parsec
